name: Wafsmp-VerAct
version: '1.0.0'
main: me.lynxid.wafsmpVerAct.WafsmpVerAct
api-version: '1.21'
load: STARTUP
authors: [ Lynxid ]
description: A Plugin used by the WafflesSMP to verify users, and track activity.
website: wafcorp.org/smp
commands:
  rules:
    description: Shows the rules of the WSMP
    permission: wafsmp.member
    usage: /<command> [p2|p3|accept]
  test:
    description: Test
    permission: wafsmp-test
    usage: /<command>
  map:
    description: Sends a link for the server map
    permission: wafsmp.member
    usage: /<command>
  reviewrules:
    aliases: rrules
    permission: wafsmp.rules
    permission-message: You do not have permission to use this command.
    description: Shows the rules of the WSMP
    usage: /<command> [player]
  rulessetup:
    aliases: rsetup
    permissions: wafsmp.rules
    permission-message: You do not have permission to use this command.
    description: Adds the default rules to the rulesconfig.yml file.
    usage: /<command>
Permissions:
  wafsmp.rules:
    description: Allows you to use the command /reviewrules
    default: op
  wafsmp.setjoinmessage:
    description: Allows you to use the command /setjoinmessage
    default: op
  wafsmp.member:
    description: Permissions for base players
    default: true
  wafsmp.*:
    description: Wildcard permission
    default: op
    children:
      wafsmp.rules: true
      wafsmp.setjoinmessage: true
      wafsmp.test: true